### ISSUE TITLE
ForImage dependency

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#1]
Dear @vmagnin,

Thank you for this project and for mentioning [ForImage](https://github.com/gha3mi/forimage) in the Discourse forum.

I forked ForColormap to add and test ForImage functionality in your project. The PNM functionality of ForImage enables the import and export of PNM files in both binary and ASCII encodings. I have provided an example for your reference.

To review the modifications, kindly visit the GitHub repository at: https://github.com/gha3mi/forcolormap

Best regards,
Ali

**Comment by vmagnin** [comment]
Thanks Ali @gha3mi for that work! That's an interesting contribution.

I was just wondering about dependencies in fpm: if forimage is a dependency of forcolormap, what happens if a user creates a project without being conscious of that fact and puts in its own `fpm.toml` file the two dependencies?
```toml
[dependencies]
forimage = {git="https://github.com/gha3mi/forimage.git"}
forcolormap = {git="https://github.com/vmagnin/forcolormap.git"}
```
Will fpm correctly manage the fact that forimage is declared two times as a dependency?

**Comment by gha3mi** [comment]
I'm happy that you find it interesting.

To answer your question, I created a new project on my local machine using fpm (0.9.0, alpha). I included two examples from ForColormap and ForImage as tests in the 'test' folder. I added my forked version of ForColormap as a dependency, as well as ForImage. The examples work correctly in my test project, which means fpm manages them correctly.

```toml
[dependencies]
forcolormap = { git = "https://github.com/gha3mi/forcolormap" }
forimage = { git = "https://github.com/gha3mi/forimage.git" }
```

Removing ForImage from dependencies has no effect, which means users of ForColormap only need to add ForColormap as a dependency, and fpm knows that ForColormap depends on ForImage.

```toml
[dependencies]
forcolormap = { git = "https://github.com/gha3mi/forcolormap" }
```

If a user wants to use ForImage in their project as well, they can add ForImage as a dependency without any issues; fpm seems to have no problem and works correctly. If you want to check these tests, I can share my simple test project with you.

_If a user accidentally adds the same dependency twice using fpm, it will result in an error:_

```toml
[dependencies]
forcolormap = { git = "https://github.com/gha3mi/forcolormap" }
forimage = { git = "https://github.com/gha3mi/forimage.git" }
forimage = { git = "https://github.com/gha3mi/forimage.git" }
```

```shell
<ERROR> *cmd_run* Package error: error: Key 'forimage' already exists
  --> fpm.toml:10:1-8
   |
 9 | forimage = { git = "https://github.com/gha3mi/forimage.git" }
   | -------- first defined here
10 | forimage = { git = "https://github.com/gha3mi/forimage.git" }
   | ^^^^^^^^ key already used
   |
STOP 1
```
